[gtk+3] Remove gtkrc post-install stuff
Gtk v3.x has deprecated gtkrc files in favour
of CSS files, so we shouldn't need this, plus
it was giving this error:

(bockbuild warning) GtkPackage instance has no attribute 'package_dir'