[gtk+3] Disable gobject-introspection
gobject-introspection is hard to compile for universal[1],
and since it's not really needed for runtime, simply disable it.

[1] One of the possible compilation problems with bockbuild:

Traceback (most recent call last):
  File "./g-ir-scanner", line 41, in <module>
    from giscanner.scannermain import scanner_main
  File "./giscanner/scannermain.py", line 34, in <module>
    from giscanner.dumper import compile_introspection_binary
  File "./giscanner/dumper.py", line 27, in <module>
    from .gdumpparser import IntrospectionBinary
  File "./giscanner/gdumpparser.py", line 31, in <module>
    from .transformer import TransformerException
  File "./giscanner/transformer.py", line 28, in <module>
    from .girparser import GIRParser
  File "./giscanner/girparser.py", line 26, in <module>
    from .girwriter import COMPATIBLE_GIR_VERSION
  File "./giscanner/girwriter.py", line 25, in <module>
    from .xmlwriter import XMLWriter
  File "./giscanner/xmlwriter.py", line 74, in <module>
    from _giscanner import collect_attributes
  File "./giscanner/libtoolimporter.py", line 66, in load_module
    mod = imp.load_module(name, open(realpath), realpath, (extension, 'rb', 3))
ImportError: dlopen(./.libs/_giscanner.so, 2): no suitable image found.  Did find:
	./.libs/_giscanner.so: mach-o, but wrong architecture
make[2]: *** [GLib-2.0.gir] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2