[libtheora] fix build by using MacPorts patches
Build of libtheora was failing with these errors
(and bringing MacPorts patches fixes it):

clang: : error: : unknown argument: '-fforce-addr' [-Wunused-command-line-argument-hard-error-in-future]
error: unknown argument: '-fforce-addr' [-Wunused-command-line-argument-hard-error-in-future]clang: : nonote: : ththis will be a hard error (cannot be downgraded to a warning) in the future
:
note: this will be a hard error (cannot be downgraded to a warning) in the future
clang: : warningwawarning: : -W-Wl,-headerpad_max_install_names: 'linker' input unused

: clangheaderpad_max_install_names: 'linker' input unused
: : wawarning: : -W-Wl,-headerpad_max_install_names: 'linker' input unused

clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused
clang: error: unknown argument: '-fforce-addr' [-Wunused-command-line-argument-hard-error-in-future]
clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused
make[2]: *** [decapiwrapper.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [apiwrapper.lo] Error 1
make[2]: *** [bitpack.lo] Error 1
make[2]: *** [decinfo.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2