[packages] update libgcrypt & libgpg-error
libgcrypt 1.4.6 doesn't compile on Mavericks[0].
libgpg-error needs to be raised because this
new version of libgcrypt (1.6.3) depends on
a new version of libgpg-error (1.11).

[0] More than 20 errors like:

mpih-div.c:84:14: error: invalid use of a cast in a inline asm context requiring an l-value: remove the cast or build with -fheinous-gnu-extensions
                udiv_qrnnd(divisor_limb_inverted, dummy,
                ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./longlong.h:463:23: note: expanded from macro 'udiv_qrnnd'